# Generated by Django 5.2.1 on 2025-05-27 08:05

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='Это скважина?')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Modbus устройства')),
                ('modbus_port', models.IntegerField(default=502, verbose_name='Порт Modbus')),
                ('native_id', models.IntegerField(blank=True, null=True, verbose_name='NATIVE_ID (Modbus register)')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='CODE параметра')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web_ui.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
